### ISSUE TITLE
Add "app creator's chart" type labelling of charts

### ISSUE THREAD

**Issue by naseemkullah** [helm/hub#111]
For example: https://hub.helm.sh/charts?q=cert-manager

A few cert-managers available, would be nice to know that jetstack make cert-manager which might help you make a decision.

Similarly with kibana here: https://hub.helm.sh/charts?q=kibana

**Comment by scottrigby** [comment]
See #41

**Comment by naseemkullah** [comment]
Thanks @scottrigby
