### ISSUE TITLE
jfrog Charts don't display in a normal way

### ISSUE THREAD

**Issue by zzxwill** [helm/hub#115]
Charts from `jfrog` https://hub.helm.sh/charts/jfrog doesn't show correctly. There are so much space between those Charts above and those of below.
![20190702171317](https://user-images.githubusercontent.com/2805315/60500366-ca31ff80-9cec-11e9-8787-c854bf315a1d.jpg)

**Comment by Dean-Coakley** [comment]
Submitted a fix, note that this bug applies to other multi row chart lists too.

Such as: https://hub.helm.sh/charts/appscode
