### ISSUE TITLE
[bug] Listing display whitespace

### ISSUE THREAD

**Issue by stefanprodan** [helm/hub#187]
The listing display is buggy, I've tested it on Chrome, Opera and Safari:
![aws](https://user-images.githubusercontent.com/3797675/69656052-80252e00-1080-11ea-81c8-8878aee991c2.png)

**Comment by lindhe** [comment]
I'm guessing they only need to update to the latest version of Monocular, because hub.kubeapps.com don't seem to have the same issue.

**Comment by scottrigby** [comment]
Related to #212

**Comment by mattfarina** [comment]
This was fixed in upstream Monocular. Since the Helm Hub is now redirecting to the Artifact Hub, I'm closing this issue as it's no longer relevant.
