### ISSUE TITLE
Create documentation for running chart repo in object storage

### ISSUE THREAD

**Issue by mattfarina** [helm/hub#2]

**Comment by prydonius** [comment]
Is that in the purview of this project, I wonder if this is something that should be in the charts or Helm docs?

**Comment by mattfarina** [comment]
It's a task we need to handle as part of the launch for a good experience for chart distributors. Shouldn't we group all of those issues together so we can work on the total experience rather than on a piece of software?

Note, distributors are the No. 2 in priority order for our profiles... https://github.com/helm/community/blob/master/user-profiles.md

hub is a bit of a solution rather than a single piece of software. It's monocular + docs + hosting + process.

**Comment by prydonius** [comment]
@mattfarina sure, I guess my question is more about where this documentation should live. Do we plan for it to be in this repo, or is the end goal to add it to docs.helm.sh?

**Comment by mattfarina** [comment]
@prydonius I would expect it to run on docs.helm.sh. Though, I would like to break out and be in a repo of its own. But, I'll wait until after the governance lands to deal with that.

**Comment by rimusz** [comment]
I would put docs to this repo and make it accessible from monocular/hub.helm.sh

**Comment by mattfarina** [comment]
I opened an issue to document this over on helm.sh. Closing here as it's no longer relevant here.
