### ISSUE TITLE
Add stable repo information to the hub (for the next 6 months)

### ISSUE THREAD

**Issue by scottrigby** [helm/hub#210]
Helm 3 users no longer know how to add the stable repo to install charts from there. We should now list that on the hub. Example: https://hub.helm.sh/charts/stable/airflow

I added the 6 month note because of [Status of the Project](https://github.com/helm/charts/#status-of-the-project) and [Deprecation Timeline](https://github.com/helm/charts/#deprecation-timeline). So it's temporary, but important.

**Comment by phumberdroz** [comment]
Looking at this commit this should already been implemented but not deployed? 
https://github.com/helm/monocular/commit/14026537146382f5a386059d63c47837bad15ba1

**Comment by scottrigby** [comment]
Nice, thanks for looking for that. We should build a new Monocular release and deploy to the Hub. Let's keep this open till we do

**Comment by scottrigby** [comment]
Created new Monocular release https://github.com/helm/monocular/releases/tag/v1.9.0. Will still need to deploy the new version to the hub.

**Comment by dns2utf8** [comment]
After theses 6 months there should be a hint that the default repo is unsupported at that time.

**Comment by kfox1111** [comment]
This has been a problem for me several times over the last month or so.

Helm 3 isn't shipping the stable repo. Going to any of the stable entries in hub.helm.sh does not tell you like any other repo how to add the repo to helm.

Now that helm 3 is released, the stable repo should not be treated specially by the website now.

**Comment by xeor** [comment]
I guess the "next 6 months" are here soon... Should we wait? I don't see a note yet, and I still think I need to do `helm repo add stable https://kubernetes-charts.storage.googleapis.com`..

**Comment by Gerromie** [comment]
As @xeor mentioned, the clock is running down on the deprecation schedule. All indications and links that I've found lead to information that the documentation (including 3.2.1) has been updated with steps to `helm repo add` the default stable repository. However, this links to the deprecated repository still. 

https://helm.sh/docs/intro/quickstart/#initialize-a-helm-chart-repository

If at all possible, I'd like to be ahead of the deprecation change and migrate to the proper stable repository before the cutoff deadline. 

Thanks for your consideration and any advice you may provide.

**Comment by mattfarina** [comment]
Closing as it no longer applies. The Helm Hub is deprecated.
