### ISSUE TITLE
Grafana Chart now showing

### ISSUE THREAD

**Issue by phumberdroz** [helm/hub#223]
I am not sure if this is an Issue for this Repo or is better to be posted to monocular

https://hub.helm.sh/charts?q=grafana

Does not show the `stable/grafana` chart and I am unsure what could be causing this since it is reachable here: https://hub.helm.sh/charts/stable/grafana

**Comment by scottrigby** [comment]
I believe this is a duplicate of https://github.com/helm/hub/issues/187. This is an issue with the whitespace… scroll down and you should see the chart.

**Comment by phumberdroz** [comment]
oh 👍
