### ISSUE TITLE
Issue with helm chart repo for Citrix on Helm HUB

### ISSUE THREAD

**Issue by priyankash-citrix** [helm/hub#229]
We had few helm charts in two different repositories and we have recently moved them into a single GitHub helm repository. Details of the current repo:
  - name: citrix
    url: https://citrix.github.io/citrix-helm-charts/

But on https://hub.helm.sh, still the old chart repo named "cic" is getting reflected containing charts with old version. This helm repo is not there anymore and it shouldn't be visible on https://hub.helm.sh. Please look into it.

Screenshot showing the same:
<img width="1440" alt="Screenshot 2020-01-12 at 9 08 02 PM" src="https://user-images.githubusercontent.com/43474200/72221333-c1659480-357f-11ea-9fde-cb8e09feb1aa.png">

**Comment by mattfarina** [comment]
This was due to a caching bug. I refreshed the cache and the listing is now fixed.
