### ISSUE TITLE
"Need Helm?" link is broken from the "Install" panel of the chart info on Helm Hub

### ISSUE THREAD

**Issue by bczoma** [helm/hub#238]
This seems to be the case for all charts.

The link is currently pointing to https://github.com/helm/helm/blob/master/docs/quickstart.md

Assuming it should point to https://helm.sh/docs/intro/quickstart/

**Comment by mattfarina** [comment]
Thanks for reporting the issue

**Comment by Asday** [comment]
This remains the case.

**Comment by cpanato** [comment]
I will take a look

/assign

**Comment by bridgetkromhout** [comment]
While the change in https://github.com/helm/monocular/pull/673 does seem to be a correct and necessary change, it does not appear to resolve the reported issue. The incorrect link points to github, although I do not see where that link is being generated (at least, it does not seem to be in this repo). Thoughts?

**Comment by mattfarina** [comment]
Closing as there is a monocular issue and the Helm Hub is now deprecated.
