### ISSUE TITLE
Maintainers links broken on Helm Hub if email not provided

### ISSUE THREAD

**Issue by bczoma** [helm/hub#240]
According to https://helm.sh/docs/topics/charts/, providing maintainers email in the Chart.yaml file is optional.

There should be some intelligence on the chart details page to provide a link to the URL if defined and email is missing.

Currently, clicking on a maintainer opens up an email with "undefined" in the To field. Example: https://hub.helm.sh/charts/solace/pubsubplus

**Comment by mattfarina** [comment]
Thanks for pointing out the issue.

**Comment by mattfarina** [comment]
This has an open issue against it for monocular and the Helm Hub has not been shut down and pointed to the Artifact Hub. So, I am going to close the issue.
