### ISSUE TITLE
Markdown anchors in chart's README.md redirect to https://hub.helm.sh/#anchor

### ISSUE THREAD

**Issue by karok2m** [helm/hub#283]
Markdown anchors in chart's README.md redirect to Helm Hub home page: `https://hub.helm.sh/#anchor`

For example, check redirection links on `Table of Contents` for [microsoft/azure-industrial-iot](https://hub.helm.sh/charts/microsoft/azure-industrial-iot) chart:

![Screenshot (5)](https://user-images.githubusercontent.com/20900945/77348408-b4141580-6d39-11ea-8635-e7c9c59a6b5e.png)

**Comment by mattfarina** [comment]
That's definitely a bug.  Thanks for reporting it.

**Comment by mattfarina** [comment]
This has been recorded on the monocular project and the Helm Hub has been turned down... so closing the issue.
