### ISSUE TITLE
Incorrect rending of the search result page

### ISSUE THREAD

**Issue by hbagdi** [helm/hub#287]
The search result populates the result in a weird output.
Most users don't even scroll down to see the relevant repository.

![Screenshot from 2020-03-26 13-51-31](https://user-images.githubusercontent.com/4694585/77695405-ef485b80-6f68-11ea-9a54-e056aa76832a.png)

**Comment by austince** [comment]
Can confirm that users (at least this one) won't scroll down and will think it's just not listed.

**Comment by austince** [comment]
I think this duplicates https://github.com/helm/hub/issues/187.

Not very familiar with flex-box myself, but was able to fix this issue by removing the `display: flex` and `flex: 1`  rules from the `<app-chart-list>` component, though left the flex layout on the child `section.chart-list`. 

![helm-hub-flex-issue](https://user-images.githubusercontent.com/4655775/79369303-bde6fe00-7f1e-11ea-8015-a0e857823a67.png)

**Comment by mattfarina** [comment]
This has been fixed in Monocular, the software that powered the Helm Hub. As the Helm Hub is deprecated and now points to the Artifact Hub I'm closing this issue. It no longer applies.
