### ISSUE TITLE
Search Should Return Matching Titles First

### ISSUE THREAD

**Issue by eytanhanig** [helm/hub#291]
It appears that chart searches look at both the chart titles and descriptions, however results are sorted alphabetically regardless of whether the match is in the title or the description. An example of this is when searching for `prometheus` the first result is `aerospike/aerospike`.

Until we have a more advanced sorting algorithm **I propose that search results first return charts whose title is a match followed by charts whose only match is in the description**.

**Comment by mattfarina** [comment]
That sounds like a good idea. A change like that needs to be made to the [monocular](https://github.com/helm/monocular) project.

**Comment by mattfarina** [comment]
As the Helm Hub now redirects to the Artifact Hub, I am closing this issue.
