### ISSUE TITLE
Install command needs to be modified - kuberhealthy

### ISSUE THREAD

**Issue by chadbitzer** [helm/hub#293]
Hello, the command listed in the "Install" section of: https://hub.helm.sh/charts/kuberhealthy/kuberhealthy
needs to be modified to work properly.  It's listed as `helm install kuberhealthy/kuberhealthy --version 2.1.0` but should be `helm install kuberhealthy kuberhealthy/kuberhealthy --version 2.1.0`

Is that a manual config by the helm/hub maintainers or was that generated automatically with variables from our repo?

Thanks!

**Comment by mattfarina** [comment]
@chadbitzer that's a great catch. Thanks.

**Comment by mattfarina** [comment]
The Helm Hub now redirects to the Artifact Hub. Closing this issue as it is overcome by events.
