### ISSUE TITLE
README.md markdown not rendering properly

### ISSUE THREAD

**Issue by rparth** [helm/hub#319]
We have markdown in our README showing up incorrectly on helm hub. Looks correct on artifacthub.io - Below is the markdown from our README

The default login and password to use is **_flash-admin@foo.com_ and flash-password.** You can change these in the UI once logged in.

Thanks in advance for looking into it.

**Comment by mattfarina** [comment]
It looks like you found a bug in the markdown library we use to convert to html.

**Comment by kristinnardal2** [comment]
I've found a similar bug where a code block that comes directly after a list is rendered in a different way from how github renders it. I've posted images to show the difference. Could you point me in the right direction for submitting a bug? I've a hard time figuring out what markdown library helm hub is using.

### Helm hub 
![artifactory-readme-bug](https://user-images.githubusercontent.com/61417000/91143401-c14f7a80-e6b2-11ea-8f64-1fd7b93d5ed2.png)

### Github
![artifactory-ha-github](https://user-images.githubusercontent.com/61417000/91143528-f5c33680-e6b2-11ea-9651-e31b5f89dcda.png)

**Comment by mattfarina** [comment]
As the Helm Hub is deprecated, I'm closing this issue.
