### ISSUE TITLE
RSS feed releases Helm charts

### ISSUE THREAD

**Issue by aristosvo** [helm/hub#342]
It would be really nice to have a way of subscribing via RSS to a release RSS feed for a specific chart

**Comment by mattfarina** [comment]
@aristosvo that is a great idea. The [Artifact Hub](https://artifacthub.io/) lists Helm charts and has started to add notifications. Would you mind filing a feature request over at https://github.com/artifacthub/hub

**Comment by aristosvo** [comment]
What about https://github.com/helm/monocular/pull/671?

**Comment by kingdonb** [comment]
It looks like Artifact Hub does provide RSS feeds already: https://artifacthub.io/api/v1/packages/helm/nginx/nginx-ingress/feed/rss

It might be nice to have this feature on Helm Hub as well (especially if the code is already implemented there, in helm/monocular#671)

**Comment by mattfarina** [comment]
The Artifact Hub has replaced the Helm Hub. Going to close this issue as we won't be adding it to the now deprecated site.
