### ISSUE TITLE
Width of chart page cuts off right side of README tables

### ISSUE THREAD

**Issue by jonstelly** [helm/hub#346]
Below is what I see on the [stable/traefik](https://hub.helm.sh/charts/stable/traefik) chart page.  Notice that the entire value column from the values table is missing.  I see similar in almost all charts, [cert-manager](https://hub.helm.sh/charts/jetstack/cert-manager), etc...

You can scroll the table horizontally but it's a bit challenging tracking rows since you can't have setting name and the value on the screen at the same time.  Could you bump up the content width in the CSS?  The below screenshot is on a 3440x1440 monitor but even on a 1920x1080 monitor it seems that there's some room to increase the width of the content.

I looked through existing issues and didn't see one for this but sorry if it's a duplicate.

![screenshot](https://i.imgur.com/0SROJEu.png)

**Comment by mattfarina** [comment]
Closing as the Helm Hub is deprecated and redirects to the Artifact Hub.
