### ISSUE TITLE
Cluster autoscaler version 1.15 and 1.16 stable charts are missing

### ISSUE THREAD

**Issue by jvaibhav123** [helm/hub#370]
Hello,

I was going through stable charts for cluster autoscaler for 1.15 and 1.16 version and i didnt find them on repo. Could it possible to upload them or if its available in some other repo?

Thanks in advance.

Regards,
Vaibhav

**Comment by mattfarina** [comment]
Thanks for pointing this out. I've created an issue on the autoscaler project to see about getting it added to the Artifact Hub.
