### ISSUE TITLE
[CSS] Search results appear underneath upper fold

### ISSUE THREAD

**Issue by kevin-lindsay-1** [helm/hub#373]
I initially thought that search didn't work, because I didn't see an official postgres chart due to results appearing underneath the upper fold.

![image](https://user-images.githubusercontent.com/19811360/84522991-93f35300-aca5-11ea-9ef0-32bd6c88082f.png)

```
Browser: Chrome 83.0.4103.97
OS: Windows 10
```

**Comment by schra** [comment]
Can confirm this. As a workaround, I use this uBlock Origin filter in the meantime to fix the spacing issue:

```
! see https://github.com/helm/hub/issues/373
! fix that there is a lot of space between rows in the search results
hub.helm.sh##.chart-list:style(height: min-content)
```

**Comment by mattfarina** [comment]
This issue has been fixed in Monocular, the software powering the hub. The Helm Hub now redirects to the Artifact Hub. Closing this issue.
