### ISSUE TITLE
Redirection mechanism or warning message for deprecated charts

### ISSUE THREAD

**Issue by hasancelik** [helm/hub#376]
Hi,

We have deprecated Hazelcast charts at `helm/charts` repo so charts that has `stable/hazelcast` prefix were removed from helm-hub. When one of our old users goes to those pages, they welcomed by rotating spinner:
https://hub.helm.sh/charts/stable/hazelcast
https://hub.helm.sh/charts/stable/hazelcast-jet

Do you have any redirection mechanism between deprecated(stable/hazelcast) and existing one(hazelcast/hazelcast) or can we publish warning message for these users like `please visit new helm hub page` ?

Related deprecation commits from official helm repo:
https://github.com/helm/charts/pull/22616/commits/d49277c42a70610c171e32d52981735b9c6f7a6c
https://github.com/helm/charts/pull/22617/commits/70cfc70414354f1fdd56489ce88774af22c91e6c

**Comment by mattfarina** [comment]
This is overcome by events as the stable chart repository has been removed from being listed. Closing the issue.
