### ISSUE TITLE
Some pages of Charts in hub.helm.sh don't load their README content

### ISSUE THREAD

**Issue by javimox** [helm/hub#403]
Hi,

There are a couple of pages that don't load the chart's README. The loading animated image keeps circling indefinitely.

Examples:

https://hub.helm.sh/charts/mox/confluence-server
https://hub.helm.sh/charts/mox/jira-software

This is the helm repository:
https://github.com/javimox/helm-charts

Just wanted to check if that's an issue from your side or from my side and eventually I'd like to get a hint on how to fix that.

Thank you.

**Comment by mattfarina** [comment]
There is an issue with an invalid gzip header being in the file. Helm should ignore these. We need to upgrade monocular to fix this.

I'm not sure why the header is ending up in the chart in the first place.

**Comment by javimox** [comment]
Somehow I managed to get the README loading again but it worked just temporary.

Not sure if this information is relevant here but I am using [Releaser action](https://github.com/helm/chart-releaser-action) to publish Charts.

**Comment by mattfarina** [comment]
Closing as this is overcome by the move to Artifact Hub.
