### ISSUE TITLE
Hub is not loading one of my charts

### ISSUE THREAD

**Issue by gkarthiks** [helm/hub#404]
I have my charts in https://gkarthiks.github.io/helm-charts/ and four of them are listed in the hub without issue here https://hub.helm.sh/charts/gkarthiks.

But the kafka exporter chart is not listed in the hub.

**Comment by mattfarina** [comment]
This is a duplicate of #287. If you scroll down you'll see the chart. We have a bug.

**Comment by gkarthiks** [comment]
right @mattfarina I see it in the middle of the page. Thanks!
