### ISSUE TITLE
Charts in stable repo not available due to duplicate stable repo name in repos.yaml

### ISSUE THREAD

**Issue by xoxbet** [helm/hub#414]
Hello, the last two commits to master broke _stable_ repo - _stable_ was used as the name of _sonatype_ repo in [commit1](https://github.com/helm/hub/commit/6bba6eb9448acd375152cd2d37c01557dbc00bd8#diff-dd0b4665e4e8fe7b469cbb939d746409), [commit2](https://github.com/helm/hub/commit/10c87ccc891ff0cece94f5c12e2ca71007fd5ace#diff-e083770bcee5fef1cb518788f84ffb31)

So now only sonatype charts are currently available in https://hub.helm.sh/charts/stable

I've created a pull request to fix this:
https://github.com/helm/hub/pull/413

**Comment by xoxbet** [comment]
PR was merged but API endpoint https://hub.helm.sh/api/chartsvc/v1/charts/stable still returns cached items (only sonatype charts).

**Comment by mattfarina** [comment]
@xoxbet Thanks for catching this. The PR was merged and now we just need to clear the cache.

**Comment by mattfarina** [comment]
The cache has been cleared and this is fixed. Thanks.
