### ISSUE TITLE
Longhorn Chart README page is loading indifinitely

### ISSUE THREAD

**Issue by meldafrawi** [helm/hub#438]
Longhorn page  don't load the chart's README. The loading animated image keeps circling indefinitely.

![image](https://user-images.githubusercontent.com/18232258/90169918-8dfe1900-dd9f-11ea-9406-fbe4f20bb84e.png)

https://hub.helm.sh/charts/longhorn/longhorn

Just wanted to check if that's an issue from your side or from our side.

Thanks

**Comment by mattfarina** [comment]
@meldafrawi Thanks for pointing that out. I am unable to reproduce the problem. Are you still seeing the problem? If so, can you provide some details about your browser and plugins.

**Comment by meldafrawi** [comment]
@mattfarina I can see README is loading correctly now, Thank you very much.
will close the issue.
