### ISSUE TITLE
Migration to Artifact Hub

### ISSUE THREAD

**Issue by mattfarina** [helm/hub#439]
A proposal has been put forth to migrate the Helm Hub to the Artifact Hub (a sandbox CNCF project). It is currently before a lazy consensus vote of both the chart and org maintainers.

- [x] Automate copying current repos to the Artifact Hub. There will be a process for people to claim them.
- [x] Clearly document how Helm Hub repo owners can transfer / list their repos in the Artifact Hub
- [x] Artifact Hub owners will add an endpoint so that it can be used with Helm CLI search
- [x] Helm Hub domain redirect to Artifact Hub (search MUST be completed first)
- [x] Update Helm Docs to guide people to Artifact Hub
- [x] Keep Helm Hub running in case a rollback is needed for some time then spin down
- [x] Helm blog post announcement
- [ ] Update repo Readme and description with deprecation notice #484 
- then close this issue, and archive the repo in GitHub

The reason for the Artifact Hub move is...

- It provides more automation to handle currently manual situations (it's less work for me)
- The Hub is built on Monocular which needs some love. Artifact Hub is in better shape
- Artifact Hub provides the means for self management of artifacts
- People can find more than Helm charts. This is part of being a good CNCF citizen

**Comment by mattfarina** [comment]
Note, when the vote is closed on the Helm site we'll note it here. Progress updates will also be documented here.

**Comment by tegioz** [comment]
> * [ ]  Automate copying current repos to the Artifact Hub. There will be a process for people to claim them.

This is ready to go. I've written a [small script](https://gist.github.com/tegioz/6c81dc7f2d77c66ae3c1b513e5aba7f1) that registers the repos available in Helm Hub that are not present in Artifact Hub. I can launch it on production when you are ready.

**Comment by marckhouzam** [comment]
So https://hub.helm.sh/ to https://artifacthub.io/

**Comment by technosophos** [comment]
I am SOOOO excited about this one! Artifact Hub will be such a helpful thing for the community, and I am excited that Helm will be moving that direction.

**Comment by richard-cox** [comment]
I just noticed https://hub.helm.sh now fails to show charts. Is it gone for good? If not what's the expected timeline for `Keep Helm Hub running in case a rollback is needed for some time then spin down`?

**Comment by mattfarina** [comment]
@richard-cox That was a separate bug. I'm not sure what caused it but I fixed it prior to setting up the redirect. The Helm Hub is now gone for good.

**Comment by mattfarina** [comment]
The redirect is in place, docs updated, and blog post announcement is out.

I'm going to keep this issue open until the helm hub service is formally turned down. We want to keep it going for awhile, just in case.

**Comment by mattfarina** [comment]
The has been moved over for all the things to route through artifact hub. Once the DNS migration is complete the remaining infra can be turned off.

**Comment by bridgetkromhout** [comment]
> Once the DNS migration is complete the remaining infra can be turned off.

Do any migration steps remain? Can we archive this repo on github?
