### ISSUE TITLE
Install panel "copy" doesn't work with Helm 3 and it picks "beta" chart.

### ISSUE THREAD

**Issue by datamattsson** [helm/hub#446]
It seems that the "copy" symbol from the "Install" panel doesn't generate a command that works with Helm 3, is there Helm 3 specific hub we need to use for Helm 3?

Here's an example from a chart I frequent.

```
# This is the generated CLI from the Install panel:
$ helm install hpe-storage/hpe-csi-driver --version 1.3.0-beta
Error: must either provide a name or specify --generate-name
$ helm version
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.6"}
```

The other thing is that the copied command contains the latest chart, even if it's labelled beta. If you would omit version, in my particular case, the previous stable version would be installed.

```
$ helm install hpe-csi -n hpe-csi hpe/hpe-csi-driver
NAME: hpe-csi
LAST DEPLOYED: Tue Aug 25 13:06:23 2020
NAMESPACE: hpe-csi
STATUS: deployed
REVISION: 1
TEST SUITE: None
$ helm list -n hpe-csi
NAME   	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART               	APP VERSION
hpe-csi	hpe-csi  	1       	2020-08-25 13:06:23.027499 -0700 PDT	deployed	hpe-csi-driver-1.2.1	1.2.0
```

**Comment by mattfarina** [comment]
The version pick was a bug that was fixed in upstream Helm.

Since the Helm Hub is now redirected to the Artifact Hub I'm going to close this issue.
