### ISSUE TITLE
Helm Hub fails to load due to 503 errors

### ISSUE THREAD

**Issue by mareksapota** [helm/hub#480]
https://hub.helm.sh/, https://hub.helm.sh/charts and search all show a spinner forever and never load.  Developer tools show https://hub.helm.sh/api/chartsvc/v1/charts returns a 503 and it can be confirmed with `curl`:

```
$ curl https://hub.helm.sh/api/chartsvc/v1/charts
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx/1.15.9</center>
</body>
</html>
```

**Comment by mattfarina** [comment]
@mareksapota thanks for letting us know. Sorry for the delay in responding.

**Comment by mattfarina** [comment]
This is now fixed.
