### ISSUE TITLE
Redirection issue from hub.helm to artifacthub

### ISSUE THREAD

**Issue by julie-garrone** [helm/hub#482]
Hi,

There seems to be a redirection issue for one of our chart.

The helm hub url [https://hub.helm.sh/charts/ibm-charts/ibm-odm-dev/20.2.0](https://hub.helm.sh/charts/ibm-charts/ibm-odm-dev/20.2.0) redirects to [https://artifacthub.io/charts/ibm-charts/ibm-odm-dev/20.2.0](https://artifacthub.io/charts/ibm-charts/ibm-odm-dev/20.2.0) which return "Error 404 - Page Not Found".

The working url for this version of the product seems to be [https://artifacthub.io/packages/helm/ibm-charts/ibm-odm-dev/20.2.0](https://artifacthub.io/packages/helm/ibm-charts/ibm-odm-dev/20.2.0).

We are updating the url in our documentation to point to artifacthub for our next version. 
But it would have been great for the previous version to be able to use the helm hub url redirection.

**Comment by mattfarina** [comment]
@julie-garrone Thanks for bringing this up. This issue is with artifact hub rather than helm hub or the redirect. I created an issue over at https://github.com/artifacthub/hub/issues/883 for this issue.

**Comment by julie-garrone** [comment]
@mattfarina Thanks ! It's working now
