### ISSUE TITLE
Handover of external-secrets

### ISSUE THREAD

**Issue by Flydiverny** [helm/hub#483]
Hi,

Due to external-secrets project being migrated to its own organisation (from https://github.com/godaddy/kubernetes-external-secrets to https://github.com/external-secrets/kubernetes-external-secrets)

It seems like we can't claim on artifacthub!

https://github.com/helm/hub/blob/2d965b985ac824284334fc00f18f3f0bfd87a545/config/repo-values.yaml#L195-L196

How can we resolve this?

**Comment by tegioz** [comment]
Hi @Flydiverny 

I've just updated the url of the repository for you. You can now proceed with the [ownership claim](https://artifacthub.io/docs/topics/repositories/#ownership-claim) process as the repository still belongs to the Helm organization. You may also be interested in the [verified publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status or the [official](https://artifacthub.io/docs/topics/repositories/#official-status) one, if it applies.

If you have any other problem related to Artifact Hub, please file an [issue in the project repository](https://github.com/artifacthub/hub/issues). Thanks!

**Comment by Flydiverny** [comment]
Thanks @tegioz! I've now successfully claimed the repo to the external-secrets organisation on artifacthub 🎉
Hopefully verified pops up with the next scan and then I can look into official as well!

Closing this 👍
