### ISSUE TITLE
Provide direction on reporting chart problems

### ISSUE THREAD

**Issue by mattfarina** [helm/hub#6]
When a chart has a security issue or other problem people will want a method to report those. We should provide direction (and maybe automation to make things easier).

**Comment by stackedsax** [comment]
I think a link to the github repo from which the chart was built would suffice.  For me, that's the missing link here.

From my discussion with @maorfr on this issue: https://github.com/helm/charts/pull/13775#issuecomment-494271416

> Self-hosting a helm chart allows people to install it sooner, I understand. However, it doesn't give people a clear location to submit feedback or issues on a chart. If I happen to take the github pages approach, perhaps someone might intuit that I'm hosting the code for the chart in the associated repo. But let's say I host my charts in a repo on some cloud provider -- how do you know where the code that built that chart lives? You could look up the associated repository in the repo-values.yaml file but that only tells you where the .tgz form of the chart lives. Maybe you get lucky and the chart owner includes a page that links to the location of the chart code, like:
>
>  - https://weaveworks.github.io/flux/
>
>But just as often, you'll be met with something like this:
>
>  - https://raw.githubusercontent.com/IBM/charts/master/repo/stable/
>
>If someone is really persistent, maybe they'll untar the .tgz, find my github username as a maintainer of the chart, look me up on github, find which repos I've contributed to and figure out where the code lives and finally submit an issue. Just as likely: they'll untar the chart and just check it in to their own personal github repo and start making changes -- exactly what I don't want to have happen.

It would be most wonderful if the task of creating the chart automatically determined what branch of what git repo the chart was being built from and then included that as part of the metadata about the chart.  But, failing something fancy like that, I'd take a manually-updated field in the `Chart.yaml` file.  That would probably get people close to the action, at least.

**Comment by scottrigby** [comment]
It would be good to link to chart source code, given that the goal of this project is for public sharing of charts.

**Comment by mattfarina** [comment]
Closing as this no longer applies. The Helm Hub is deprecated.
