### ISSUE TITLE
Add link to github repo

### ISSUE THREAD

**Issue by arthurk** [helm/hub#61]
It would be nice if a chart page could link to the link to the github repo (if it exists) so we can check the helm chart code before installing it.

**Comment by mattfarina** [comment]
This is already available and is not coupled to GitHub. Not all source will be on GitHub. For example, Gitlab has their source on gitlab.com.

There is a `sources` property in the `Chart.yaml` file. This can contain URLs to the source. For an example of this displaying on the hub see the related section on https://hub.helm.sh/charts/banzaicloud-stable/vault.

Is there something else you are looking for?

**Comment by jlegrone** [comment]
@arthurk what Matt said is correct. If you would like to inspect the helm chart code or output before installation, you have some other options as well:

1. View the resources that would be applied by adding _--dry-run --debug_ to the install or upgrade commands:
   ```
   helm install --dry-run --debug [chart]
   ```
2. Unpack the chart contents locally for inspection:
   ```
   helm fetch --untar [chart]
   ```

I think option 2 seems the closest to what you're asking for here, and it comes with the added benefit that you are inspecting the published artifact as opposed to the source repository (which could potentially differ or default to displaying a different version).

**Comment by arthurk** [comment]
@mattfarina yes this was what i'm looing for, i guess this is just an issue about chart maintainers having to add the repo url to the yml file
